// <auto-generated />
using System;
using Amiko.Server.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Amiko.Server.Migrations
{
    [DbContext(typeof(SqliteContext))]
    [Migration("20250719215823_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Amiko.Server.Database.Context.AttachmentContext", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MessageContextId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mimetype")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MessageContextId");

                    b.ToTable("AttachmentContext");
                });

            modelBuilder.Entity("Amiko.Server.Database.Context.ChannelContext", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ServerContextId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ServerContextId");

                    b.ToTable("ChannelContext");
                });

            modelBuilder.Entity("Amiko.Server.Database.Context.ChannelSeen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChanId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastSeen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ServId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserContextId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserContextId");

                    b.ToTable("ChannelSeen");
                });

            modelBuilder.Entity("Amiko.Server.Database.Context.InvitationContext", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("Amiko.Server.Database.Context.MessageContext", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Authors")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ChannelContextId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reactions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChannelContextId");

                    b.ToTable("MessageContext");
                });

            modelBuilder.Entity("Amiko.Server.Database.Context.ServerContext", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllowedUsers")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllowsGuest")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Character")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Color")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEphemeral")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("Amiko.Server.Database.Context.UserContext", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Character")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Color")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DependsOf")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prefix")
                        .HasColumnType("TEXT");

                    b.Property<string>("Salt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Webhook")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Amiko.Server.Database.Context.AttachmentContext", b =>
                {
                    b.HasOne("Amiko.Server.Database.Context.MessageContext", null)
                        .WithMany("Attachments")
                        .HasForeignKey("MessageContextId");
                });

            modelBuilder.Entity("Amiko.Server.Database.Context.ChannelContext", b =>
                {
                    b.HasOne("Amiko.Server.Database.Context.ServerContext", null)
                        .WithMany("Channels")
                        .HasForeignKey("ServerContextId");
                });

            modelBuilder.Entity("Amiko.Server.Database.Context.ChannelSeen", b =>
                {
                    b.HasOne("Amiko.Server.Database.Context.UserContext", null)
                        .WithMany("LastSeens")
                        .HasForeignKey("UserContextId");
                });

            modelBuilder.Entity("Amiko.Server.Database.Context.MessageContext", b =>
                {
                    b.HasOne("Amiko.Server.Database.Context.ChannelContext", null)
                        .WithMany("Messages")
                        .HasForeignKey("ChannelContextId");
                });

            modelBuilder.Entity("Amiko.Server.Database.Context.ChannelContext", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Amiko.Server.Database.Context.MessageContext", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("Amiko.Server.Database.Context.ServerContext", b =>
                {
                    b.Navigation("Channels");
                });

            modelBuilder.Entity("Amiko.Server.Database.Context.UserContext", b =>
                {
                    b.Navigation("LastSeens");
                });
#pragma warning restore 612, 618
        }
    }
}
