// <auto-generated />
using System;
using Amiko.Server.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Amiko.Server.Migrations
{
    [DbContext(typeof(SqliteContext))]
    partial class SqliteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Amiko.Server.Database.ChannelContext", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ServerContextId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ServerContextId");

                    b.ToTable("ChannelContext");
                });

            modelBuilder.Entity("Amiko.Server.Database.ChannelSeen", b =>
                {
                    b.Property<int>("ServId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChanId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastSeen")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserContextId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ServId", "ChanId");

                    b.HasIndex("UserContextId");

                    b.ToTable("ChannelSeen");
                });

            modelBuilder.Entity("Amiko.Server.Database.MessageContext", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChannelContextId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChannelContextId");

                    b.ToTable("MessageContext");
                });

            modelBuilder.Entity("Amiko.Server.Database.ServerContext", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllowedUsers")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("Amiko.Server.Database.UserContext", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Character")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Color")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DependsOf")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prefix")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Amiko.Server.Database.ChannelContext", b =>
                {
                    b.HasOne("Amiko.Server.Database.ServerContext", null)
                        .WithMany("Channels")
                        .HasForeignKey("ServerContextId");
                });

            modelBuilder.Entity("Amiko.Server.Database.ChannelSeen", b =>
                {
                    b.HasOne("Amiko.Server.Database.UserContext", null)
                        .WithMany("LastSeens")
                        .HasForeignKey("UserContextId");
                });

            modelBuilder.Entity("Amiko.Server.Database.MessageContext", b =>
                {
                    b.HasOne("Amiko.Server.Database.ChannelContext", null)
                        .WithMany("Messages")
                        .HasForeignKey("ChannelContextId");
                });

            modelBuilder.Entity("Amiko.Server.Database.ChannelContext", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Amiko.Server.Database.ServerContext", b =>
                {
                    b.Navigation("Channels");
                });

            modelBuilder.Entity("Amiko.Server.Database.UserContext", b =>
                {
                    b.Navigation("LastSeens");
                });
#pragma warning restore 612, 618
        }
    }
}
