name: CI

on: [ push, pull_request ]

jobs:
  api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    - name: Install dotnet EF tool
      run: dotnet tool install --global dotnet-ef
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Create release
      run: dotnet publish -c Release -r linux-x64
    - name: Generate database
      working-directory: ./server/Amiko.Database
      run: dotnet ef database update

    - uses: actions/upload-artifact@v4
      with:
        name: back
        path: server/Amiko.Server/bin/Release/net9.0/linux-x64/publish/
        if-no-files-found: error

  app:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./client

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        cache-dependency-path: 'client/package-lock.json'
    - name: Install JS dependencies
      run: npm i
    - name: Prepare scripts
      run: npm run appprep
    - name: Make executable
      run: npm run appbuild

    - uses: actions/upload-artifact@v4
      with:
        name: software
        path: |
          client/out/make/squirrel.windows/x64/
        if-no-files-found: error

  web:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./client

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        cache-dependency-path: 'client/package-lock.json'
    - name: Install JS dependencies
      run: npm i
    - name: Make executable
      run: npm run webbuild

    - uses: actions/upload-artifact@v4
      with:
        name: web
        path: |
          client/dist/
        if-no-files-found: error